-- Tenant data is hash-partitioned by user_id.
-- The users table stays unpartitioned so email can be unique across the region.
-- Child tables use modulus 16. PostgreSQL routes each row; the application does not.

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    home_region VARCHAR(64) NOT NULL DEFAULT 'local',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS audio_files (
    user_id UUID NOT NULL,
    id UUID NOT NULL,
    original_filename TEXT NOT NULL,
    content_type TEXT NOT NULL,
    byte_size INTEGER NOT NULL,
    sha256 CHAR(64) NOT NULL,
    storage_key TEXT NOT NULL,
    duration_sec DOUBLE PRECISION,
    status TEXT NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT audio_files_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT audio_files_status_chk CHECK (status IN ('uploaded', 'processing', 'completed', 'blocked', 'failed'))
) PARTITION BY HASH (user_id);

CREATE TABLE IF NOT EXISTS audio_files_p0 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS audio_files_p1 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS audio_files_p2 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS audio_files_p3 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS audio_files_p4 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS audio_files_p5 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS audio_files_p6 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS audio_files_p7 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS audio_files_p8 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS audio_files_p9 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS audio_files_p10 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS audio_files_p11 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS audio_files_p12 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS audio_files_p13 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS audio_files_p14 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS audio_files_p15 PARTITION OF audio_files FOR VALUES WITH (MODULUS 16, REMAINDER 15);

CREATE TABLE IF NOT EXISTS transcripts (
    user_id UUID NOT NULL,
    id UUID NOT NULL,
    file_id UUID NOT NULL,
    text TEXT NOT NULL,
    storage_key TEXT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT transcripts_file_uq UNIQUE (user_id, file_id),
    CONSTRAINT transcripts_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT transcripts_file_fk FOREIGN KEY (user_id, file_id) REFERENCES audio_files (user_id, id) ON DELETE CASCADE
) PARTITION BY HASH (user_id);

CREATE TABLE IF NOT EXISTS transcripts_p0 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS transcripts_p1 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS transcripts_p2 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS transcripts_p3 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS transcripts_p4 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS transcripts_p5 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS transcripts_p6 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS transcripts_p7 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS transcripts_p8 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS transcripts_p9 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS transcripts_p10 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS transcripts_p11 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS transcripts_p12 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS transcripts_p13 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS transcripts_p14 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS transcripts_p15 PARTITION OF transcripts FOR VALUES WITH (MODULUS 16, REMAINDER 15);

CREATE TABLE IF NOT EXISTS analyses (
    user_id UUID NOT NULL,
    id UUID NOT NULL,
    file_id UUID NOT NULL,
    status TEXT NOT NULL,
    duration_sec DOUBLE PRECISION,
    summary TEXT,
    taxonomy JSONB,
    layer2 JSONB,
    block_reason TEXT,
    summary_strategy VARCHAR(32),
    provider VARCHAR(32),
    storage_key TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT analyses_file_uq UNIQUE (user_id, file_id),
    CONSTRAINT analyses_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT analyses_file_fk FOREIGN KEY (user_id, file_id) REFERENCES audio_files (user_id, id) ON DELETE CASCADE,
    CONSTRAINT analyses_status_chk CHECK (status IN ('completed', 'blocked', 'failed'))
) PARTITION BY HASH (user_id);

CREATE TABLE IF NOT EXISTS analyses_p0 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS analyses_p1 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS analyses_p2 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS analyses_p3 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS analyses_p4 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS analyses_p5 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS analyses_p6 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS analyses_p7 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS analyses_p8 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS analyses_p9 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS analyses_p10 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS analyses_p11 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS analyses_p12 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS analyses_p13 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS analyses_p14 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS analyses_p15 PARTITION OF analyses FOR VALUES WITH (MODULUS 16, REMAINDER 15);

CREATE TABLE IF NOT EXISTS prompt_configs (
    user_id UUID NOT NULL,
    selections JSONB NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id),
    CONSTRAINT prompt_configs_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) PARTITION BY HASH (user_id);

CREATE TABLE IF NOT EXISTS prompt_configs_p0 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS prompt_configs_p1 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS prompt_configs_p2 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS prompt_configs_p3 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS prompt_configs_p4 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS prompt_configs_p5 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS prompt_configs_p6 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS prompt_configs_p7 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS prompt_configs_p8 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS prompt_configs_p9 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS prompt_configs_p10 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS prompt_configs_p11 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS prompt_configs_p12 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS prompt_configs_p13 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS prompt_configs_p14 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS prompt_configs_p15 PARTITION OF prompt_configs FOR VALUES WITH (MODULUS 16, REMAINDER 15);

CREATE TABLE IF NOT EXISTS rollup_summaries (
    user_id UUID NOT NULL,
    id UUID NOT NULL,
    group_by VARCHAR(64) NOT NULL,
    time_from TIMESTAMP,
    time_to TIMESTAMP,
    trigger VARCHAR(32) NOT NULL,
    result JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT rollup_summaries_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT rollup_summaries_group_chk CHECK (group_by IN ('user', 'taxonomy_label', 'week', 'sentiment')),
    CONSTRAINT rollup_summaries_trigger_chk CHECK (trigger IN ('schedule', 'on_demand'))
) PARTITION BY HASH (user_id);

CREATE TABLE IF NOT EXISTS rollup_summaries_p0 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS rollup_summaries_p1 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS rollup_summaries_p2 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS rollup_summaries_p3 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS rollup_summaries_p4 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS rollup_summaries_p5 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS rollup_summaries_p6 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS rollup_summaries_p7 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS rollup_summaries_p8 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS rollup_summaries_p9 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS rollup_summaries_p10 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS rollup_summaries_p11 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS rollup_summaries_p12 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS rollup_summaries_p13 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS rollup_summaries_p14 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS rollup_summaries_p15 PARTITION OF rollup_summaries FOR VALUES WITH (MODULUS 16, REMAINDER 15);

CREATE TABLE IF NOT EXISTS file_events (
    user_id UUID NOT NULL,
    id UUID NOT NULL,
    file_id UUID NOT NULL,
    filename TEXT NOT NULL,
    message TEXT NOT NULL,
    seq BIGINT NOT NULL,
    stage TEXT,
    level TEXT NOT NULL DEFAULT 'info',
    duration_ms INTEGER,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (user_id, id),
    CONSTRAINT file_events_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT file_events_file_fk FOREIGN KEY (user_id, file_id) REFERENCES audio_files (user_id, id) ON DELETE CASCADE,
    CONSTRAINT file_events_level_chk CHECK (level IN ('info', 'error'))
) PARTITION BY HASH (user_id);

CREATE TABLE IF NOT EXISTS file_events_p0 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE IF NOT EXISTS file_events_p1 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE IF NOT EXISTS file_events_p2 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE IF NOT EXISTS file_events_p3 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE IF NOT EXISTS file_events_p4 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE IF NOT EXISTS file_events_p5 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE IF NOT EXISTS file_events_p6 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE IF NOT EXISTS file_events_p7 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE IF NOT EXISTS file_events_p8 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE IF NOT EXISTS file_events_p9 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE IF NOT EXISTS file_events_p10 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE IF NOT EXISTS file_events_p11 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE IF NOT EXISTS file_events_p12 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE IF NOT EXISTS file_events_p13 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE IF NOT EXISTS file_events_p14 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE IF NOT EXISTS file_events_p15 PARTITION OF file_events FOR VALUES WITH (MODULUS 16, REMAINDER 15);

ALTER TABLE audio_files ADD COLUMN IF NOT EXISTS stage TEXT NOT NULL DEFAULT 'upload';

CREATE INDEX IF NOT EXISTS audio_files_user_created_idx ON audio_files (user_id, created_at);
CREATE INDEX IF NOT EXISTS file_events_user_seq_idx ON file_events (user_id, seq);
CREATE INDEX IF NOT EXISTS analyses_user_created_idx ON analyses (user_id, created_at);
CREATE INDEX IF NOT EXISTS analyses_user_status_idx ON analyses (user_id, status);
CREATE INDEX IF NOT EXISTS rollup_summaries_user_created_idx ON rollup_summaries (user_id, created_at);

